### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [coleifer/sqlite-web#100]
Hey there!

I belong to an open source security research community, and a member (@0xdhinu) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by coleifer** [comment]
You can email me at my github username at gmail.com.

**Comment by coleifer** [comment]
I'm not interested in signing up for your service. Can you please email me the details at the above?

**Comment by JamieSlome** [comment]
@coleifer - not a problem at all! I have sent you an e-mail with a link that allows you to view the report without signing-up 👍

**Comment by coleifer** [comment]
The redirect issue is not a credible threat, in my opinion, but it is resolved anyways.
