### ISSUE TITLE
Edit Table Data?

### ISSUE THREAD

**Issue by randyg3000** [coleifer/sqlite-web#106]
Great project!

Is it possible to ask for the ability to directly EDIT table data? I.e. change data in a table and ADD or DELETE a row to a table?

Thanks for your efforts and consideration!

**Comment by coleifer** [comment]
This has been requested before (see closed issues) - I have no plans at the moment, as it entails quite a bit of additional complexity. The best way to do this at present is to use the query tab to execute the appropriate INSERT/UPDATE/DELETE queries.

**Comment by coleifer** [comment]
This has been added in master and, after a little while for people to have a chance to try it out, will be incorporated into the next release. Screenshots are on the README.

**Comment by Dabunew** [comment]
Is this available now? Thanks!
