### ISSUE TITLE
Feature Request - Query History

### ISSUE THREAD

**Issue by diginfo** [coleifer/sqlite-web#108]
Firstly thanks for the time you have put into this, I am using this on home assistant.

But it would be REALLY nice, if the query box can remember it's queries & save them into local_storage so that you can use the up/down keys to select previously entered queries.

on home assistant the page refreshes after a while, and any query you have entered is removed and I have to recreate it again which can be quite frustrating.

Adding the ability to use the up and down keys to navigate & select previous queries, for me would be a huge time-saver.

Thanks again

**Comment by coleifer** [comment]
I've added a test implementation in this commit: c40fe9c95e271721bb1fa0ec2c2531f36710f192 (shift + up/down for recent queries). This is released now in v 0.4.1.
