### ISSUE TITLE
Accessing a table throws  a AttributeError

### ISSUE THREAD

**Issue by jitendranair** [coleifer/sqlite-web#11]
https://gist.github.com/anonymous/f531d279757afb75bdff

**Comment by jjlorenzo** [comment]
me too

**Comment by coleifer** [comment]
Thanks, sorry I just totally lost this in the shuffle @jitendranair

**Comment by jjlorenzo** [comment]
Thanks to you

**Comment by coleifer** [comment]
Pushing 0.1.4 to Pypi
