### ISSUE TITLE
Support for accents in url prefix

### ISSUE THREAD

**Issue by caph1993** [coleifer/sqlite-web#113]
Hello. I tried launching `sqlite_web` with the url prefix `café-de-colombia/database`, but when accessing from the browser I receive `URL does not match application prefix.` I also tried setting the url prefix to  `caf%C3%A9-de-colombia/database` and it didn't work either. Without the accent it works, so it's an accent issue. 

This is the command I am running: `SQLITE_WEB_PASSWORD=myPassword python3 -m sqlite_web --port=23042 --url-prefix=café/database --no-browser --password example_data/database.db`

Could you please add support for accents in the url-prefix?

**Comment by coleifer** [comment]
I don't intend to add this at present
