### ISSUE TITLE
New version (strict table support)

### ISSUE THREAD

**Issue by Mikescher** [coleifer/sqlite-web#117]
Hey, I'm using your web interface with sqlite table that uses strict tables [1].  
The current docker image does not support them (throws a parsing error on startup).

But your pewee library supports them. Currently I simply build the docker container locally ad pushed it on my own registry.  
If you find time you could build a new docker container (which uses the new version of pewee) to support strict tables.

Regards  
 ~ Mike

[1] https://www.sqlite.org/stricttables.html

**Comment by coleifer** [comment]
The Dockerfile is provided so you can build your own at any time.
