### ISSUE TITLE
No Insert tab

### ISSUE THREAD

**Issue by MatyasGreff** [coleifer/sqlite-web#118]
sqlite-web==0.4.1
There is no Insert tab in the UI.
![image](https://github.com/coleifer/sqlite-web/assets/60545340/bf6511fd-c821-48dd-9d81-15402cff89ec)

**Comment by coleifer** [comment]
Yeah until just now it was only available in `master`. I've gone ahead and tagged a new release, 0.5.0, which includes these changes.
