### ISSUE TITLE
No edit/delete options for records

### ISSUE THREAD

**Issue by MatyasGreff** [coleifer/sqlite-web#119]
Great project, thanks for the insert tab, works great!
This is the last addition I would need to make this tool perfect:
![image](https://github.com/coleifer/sqlite-web/assets/60545340/8d6cf14f-c44e-4fee-b3cd-ab36983a238e)

Thanks!

**Comment by coleifer** [comment]
Edit and delete require that your table has a primary key. Yours does not appear to:

https://user-images.githubusercontent.com/60545340/248600726-bf6511fd-c821-48dd-9d81-15402cff89ec.png

**Comment by MatyasGreff** [comment]
Duh.. Thanks again :)
