### ISSUE TITLE
Editing and deleting not working

### ISSUE THREAD

**Issue by LunarTwilight** [coleifer/sqlite-web#121]
When I try to delete or edit a row I get this error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/peewee.py", line 7024, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.10/dist-packages/peewee.py", line 4389, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range
```
but there's also exceptions that happen when handling that exception apparently, and also the website shows a different error (along with exceptions that happened when handling that exception), so I'm not exactly sure what the issue is
![image](https://github.com/coleifer/sqlite-web/assets/13520392/2947532e-5bfc-4c47-8693-87ba43de75b4)

The errors only happen with some rows (seems like it might be due to it having a space or something?), trying to edit or delete other rows either shows the UI as expected, or returns a 404.

**Comment by coleifer** [comment]
Can you share the schema and an example row from the table that has the issue?

**Comment by coleifer** [comment]
I've added a patch which fixes the TypeError -- this looks to be a situation where the serialization of your composite primary key has some kind of issue. Possibly the values that make up the key are very long?

If you can provide a minimal schema and an example failing row data so I can try to replicate, I'll be happy to reopen and provide a fix.

**Comment by LunarTwilight** [comment]
Updated to 0.5.2 and it's looking like it's due to the row containing NULL, as other rows that don't have a NULL value are fine.

The table's schema is ```
CREATE TABLE "filters"  (
  "regex"	TEXT,
  "action"	TEXT,
  "duration"	TEXT,
  "shouldDelete"	INTEGER
)
``` and for an example row, `regex` can be "example", `action` can be "delete", `duration` is NULL, and `shouldDelete` is 0.

**Comment by coleifer** [comment]
Does that table have a primary key? And if so are you using nullable values as part of the primary key? I think that might be the issue and I'd suggest that you probably ought to use an integer I'd or something along those lines...

**Comment by LunarTwilight** [comment]
> Does that table have a primary key? And if so are you using nullable values as part of the primary key? I think that might be the issue and I'd suggest that you probably ought to use an integer I'd or something along those lines...

The table doesn't have a primary key

**Comment by coleifer** [comment]
Ok then that's your issue.

**Comment by LunarTwilight** [comment]
yep setting a primary key for the table fixed it, thanks

**Comment by coleifer** [comment]
If there is no primary key I was thinking that it wouldn't show any option to edit or delete, was that not the case? In other words I'm surprised you got an error, because I intended to check for the presence of a pk in order to allow those operations.

**Comment by LunarTwilight** [comment]
> If there is no primary key I was thinking that it wouldn't show any option to edit or delete, was that not the case? In other words I'm surprised you got an error, because I intended to check for the presence of a pk in order to allow those operations.

There was an option to edit/delete for every row
