### ISSUE TITLE
Value is not a numeric/real. for allow null 

### ISSUE THREAD

**Issue by rikhtehgaran** [coleifer/sqlite-web#124]
Hi, I faced another problem when I wanted to add a new record it returned an error. while I set it to allow null for these columns, while I can add records from another client. these columns fill up later by my software and I need only to fill one column. what is this?
![image](https://github.com/coleifer/sqlite-web/assets/3824913/9022f46f-89e5-405f-9c36-b8540c04ee93)

**Comment by coleifer** [comment]
You need to put either the text "NULL" or an actual number, I suppose. But as it is, you are just storing the empty string (`''`).

**Comment by rikhtehgaran** [comment]
I set default null as you can see:
![image](https://github.com/coleifer/sqlite-web/assets/3824913/6b56f8db-1c5b-425e-880b-91bd44187c54)
And get error again:
![image](https://github.com/coleifer/sqlite-web/assets/3824913/75d581f5-9bf3-430c-9017-dabd292ab69a)

**Comment by rikhtehgaran** [comment]
Also, i choose the numeric value default but get error too. it's very buggy 
![image](https://github.com/coleifer/sqlite-web/assets/3824913/80314856-7680-4919-b858-8e7b10f16a31)
Error:
![image](https://github.com/coleifer/sqlite-web/assets/3824913/cdd02ce1-088a-4246-8a8f-3a76be36c5fb)
