### ISSUE TITLE
Value is not a numeric/real. for allow null 

### ISSUE THREAD

**Issue by rikhtehgaran** [coleifer/sqlite-web#125]
I can't undrestand why you close topic without solve the problem
Also, i choose the numeric value default but get error too:
![image](https://github.com/coleifer/sqlite-web/assets/3824913/4bd53b8a-b1bb-4591-b3a0-202aedc8288c)
And Error:
![image](https://github.com/coleifer/sqlite-web/assets/3824913/2d22b1b1-ff20-4a06-a5e8-99dcdbac7cca)

**Comment by rikhtehgaran** [comment]
is it possible to uncheck the feilds by default when we want to insert?
![image](https://github.com/coleifer/sqlite-web/assets/3824913/b71126ca-ef4f-4ca9-843e-522594f78061)

**Comment by coleifer** [comment]
The issue, as I stated in the one I closed, is that you are attempting to insert an empty string (`''`) into integer and real fields. Presumably you intend or wish to store NULL - in which case, you type in NULL:

![im-1691183215592](https://github.com/coleifer/sqlite-web/assets/119974/93cbceeb-6be2-4674-a701-74df437987cf)
![im-1691183225790](https://github.com/coleifer/sqlite-web/assets/119974/cfb38333-e5f2-412f-8c49-3ef3a6702561)

You might also try updating to the latest version, 0.5.1 as I did push a fix today for integerfields with null.

>is it possible to uncheck the feilds by default when we want to insert?

Sure, just added a patch: 17ccb630596d359e92a46f882f749dfb5e767ebb
