### ISSUE TITLE
Suggestion Features

### ISSUE THREAD

**Issue by rikhtehgaran** [coleifer/sqlite-web#126]
Hi is it possible 1. to show views in the left sidebar and 2. can sort fields generated by selecting a query with a mouse click like the content tab
![image](https://github.com/coleifer/sqlite-web/assets/3824913/c8a47b49-cc6b-42da-9094-c84e623c386a)

**Comment by coleifer** [comment]
First cut at ordering on the query tab:

0b39cc159bebf7aba157a4e725b38e08e8ccb54b and c53738bec2dd5d180b1e67076e323c064bb92f14

Views added f056311
