### ISSUE TITLE
Hide long value from list

### ISSUE THREAD

**Issue by rikhtehgaran** [coleifer/sqlite-web#127]
Hi I tried to see my view in sqlite_master but it doesn't show completely because that value is too long also I click on three dot's but nothing happened and it's only # 
![image](https://github.com/coleifer/sqlite-web/assets/3824913/c47cd923-d727-4a4a-8763-51c293a4c82a)

**Comment by coleifer** [comment]
Thanks this is fixed now.

**Comment by rikhtehgaran** [comment]
How can I update my package? is it possible from pip?

**Comment by coleifer** [comment]
Yeah it depends how you installed it. But yes "pip install -U sqlite-web" should work.
