### ISSUE TITLE
Support multiple DB's

### ISSUE THREAD

**Issue by aersam** [coleifer/sqlite-web#135]
Hi there

I would like to use sqlite_web to display the gui for multiple db's, which almost works since I can use multiple calls to initialize_app. However, the globals in sqlite_web.py are a deal breaker. Would you accept a PR that simply turns the globals to a dict with the file_name as key or something the like?

**Comment by coleifer** [comment]
No plans for supporting this at the moment.

**Comment by aersam** [comment]
Ok, I implemented it myself: https://github.com/bmsuisse/sqlite-web/tree/poetry 
However the code has lots of changes:
- Switched to poetry
- removed version checks, as I have the versions in poetry now
- Python 2 support dropped

Just in case you want to have a look at it, feel free to use whatever you want

**Comment by asyba** [comment]
@coleifer any news about supporting multiple database? maybe a environment  variable to select a folder with many DB files.
and then on the UI select one of this DB and view it etc?
