### ISSUE TITLE
admin password is not encrypted and it's not secure 

### ISSUE THREAD

**Issue by rikhtehgaran** [coleifer/sqlite-web#137]
Hi for putting the password we should define the environment password like this: SQLITE_WEB_PASSWORD=<password> it's not secure I suggest another password type like md5. it means I put a password in md5 format but in the browser, I enter the normal password

**Comment by coleifer** [comment]
bro it's perfectly fine.

**Comment by rikhtehgaran** [comment]
Do you mean there is no need to add this option? 
I disagree I don't want to store my password on the server

**Comment by coleifer** [comment]
Your database presumably lives on the server as well… but more generally you can put nginx or anything else in front of the app and use them for auth if you prefer.
