### ISSUE TITLE
Forgotten DockerHub image

### ISSUE THREAD

**Issue by GeiserX** [coleifer/sqlite-web#141]
I would like to ask, please, to keep updating the official docker image hosted at DockerHub: https://hub.docker.com/r/coleifer/sqlite-web

Additionally, the only available tag is `latest` which is sad. Could you follow the same version number that you're using for this software, so we can pin a version and upgrade it consciously?

**Comment by coleifer** [comment]
The dockerfile is provided so you can build it yourself.

**Comment by GeiserX** [comment]
Hey @coleifer yes, it's the method I'm using now, but I'm running it in a resource-constrained VM in the cloud, so the build process takes a very long time, and consumes precious resources. Having an official image from you would be a far better option for my use case, to ease the deployment and liberate disk space there. It would be a hassle for me to build my own image and have to maintain it, which only benefits me. Instead, having your image available as a source of authority, could benefit more people which are in a similar situation.

**Comment by nanoscopic** [comment]
For anyone wanting a build newer than 4 years ago for linux-amd64: https://hub.docker.com/r/dryark/sqlite-web/tags
