### ISSUE TITLE
Bookmark drop down in query not visible on IOS devices

### ISSUE THREAD

**Issue by PhilipCraigAU** [coleifer/sqlite-web#142]
G'day 
I have a number of sqlite queries saved in bookmarks which work well from a pc browser, but don't display in the Home Assistant app on apple devices
image
![image](https://github.com/coleifer/sqlite-web/assets/148041881/4b28c631-0fbe-44c1-96cc-7c22357831ea)

**Comment by coleifer** [comment]
They’re just in local storage on the browser. I assume that data only exists on your main computer and not your phone.

**Comment by PhilipCraigAU** [comment]
Thanks so much.
That was exactly the issue. I didn't realize they weren't part of the program & persistent across all devices.
And for those playing at home... Deleting browser data / cookies etc removes these bookmarks.
Appreciate the fast response. 
![IMG_9477](https://github.com/coleifer/sqlite-web/assets/148041881/034a4574-c0d6-4ce3-9944-908e5401c2b9)
