### ISSUE TITLE
Log file is not created and logging is printed to console

### ISSUE THREAD

**Issue by vrtareg** [coleifer/sqlite-web#143]
Hi

I have noticed that even if I provide `-l LOG_FILE, --log-file=LOG_FILE` it does not produce log file.

All printed to console.

Latest version 0.6.3

Regards,
Areg

**Comment by coleifer** [comment]
This is not correct - the handler is added but by default it only logs at `warning` level or above. For example, if you open up the query tab and type in a nonsense query, it will log this into the logfile with a full traceback. I believe the log file is working as-intended.

There are other logs generated, for example by the werkzeug library when using the development server -- these are not included in the sqlite-web log file.
