### ISSUE TITLE
coleifer/sqlite-web on DockerHub seems not to be up to date

### ISSUE THREAD

**Issue by MatthiasDE** [coleifer/sqlite-web#151]
Hello,

had some testings with the pypi module and found in your readme that there is also Docker support. So I tried to download it from Docker Hub spinning it on. Makes it easier from admin perspective to use already a prepared container rather than building one if possible.

Could it be that this is a quite old version there? In Docker Hub it states that it was updated 3 years ago and when using the  sqlite-web then also my views that I created in the SQLite DB seems to be gone (even when using the same file).

Maybe it could make sense to include version number in the interface that fast identification could be done if e.g. pypi package is different from the Docker Hub Container?

BR Matthias

**Comment by coleifer** [comment]
Yeah I don't really mess with docker hub any more, it's a bit of a pain and the Dockerfile is provided in the repo so there's no need.

>Maybe it could make sense to include version number in the interface

That's a great idea, will add.

**Comment by coleifer** [comment]
That's done now.

**Comment by nanoscopic** [comment]
"no need". It's needed for anyone who is using NPM via the web interface. You can't use local images there and have to put a registry link in.

Fwiw I built this off the current commit https://hub.docker.com/r/dryark/sqlite-web/tags
