### ISSUE TITLE
Serve sqlite-web in a flask end point

### ISSUE THREAD

**Issue by arnerak** [coleifer/sqlite-web#152]
Hey there!

I'm looking for a way to serve sqlite-web in a flask end point of an existing app. Something along the lines of:
```
@app.route('/db/<path:path>')
def db(path):
    # render sqlite-web for given path
```

Is this somehow achievable with the current implementation?

Thank you for the great project :)

**Comment by coleifer** [comment]
These appear to be the relevant docs:

https://flask.palletsprojects.com/en/2.3.x/patterns/appdispatch/#
