### ISSUE TITLE
Values are truncated

### ISSUE THREAD

**Issue by aicioara** [coleifer/sqlite-web#154]
At the moment, cell values are truncated at 50 characters. Ellipsis (...) are shown on the trail, and clicking those allows us to expand to the entire cell text. However, when pressed, the entire table shifts, so I lose my cell. Is there an option to display the full content of the cell right away, without the need to click the ellipsis?

**Comment by coleifer** [comment]
Added a new option, `-T` or `--no-truncate`, which will disable the ellipsis stuff.
