### ISSUE TITLE
Disable hotkeys

### ISSUE THREAD

**Issue by aicioara** [coleifer/sqlite-web#155]
Currently, in the `Query` tab, on macOS, <kbd>shift</kbd>+<kbd>↑</kbd> and <kbd>shift</kbd>+<kbd>↓</kbd> toggle between previous SQL commands. This means that I cannot use the regular `<input>` to select text as I please. Is there an option to disable these hotkeys?

**Comment by coleifer** [comment]
Sorry not at the moment.
