### ISSUE TITLE
Insert Tab checks all fields

### ISSUE THREAD

**Issue by nanoscopic** [coleifer/sqlite-web#156]
The 'Insert' tab on a table checks all the fields by default.

It would be more helpful if it only checked the fields that are required / don't have a default by default.

Imo it seems it would even be preferable to not check any of the boxes to begin with and to auto-check a box once any content is put in the box. That would be an easy solve compared to determining which fields are required.

**Comment by coleifer** [comment]
I've decided that unchecking cols w/defaults is a fine idea and have added this.

**Comment by nanoscopic** [comment]
Thank you that's very helpful.
