### ISSUE TITLE
ARM64 build is broken

### ISSUE THREAD

**Issue by nanoscopic** [coleifer/sqlite-web#157]
If I attempt to cross-compile an arm64 build of this the build fails.

I updated the base image to arm64v8/python:3-alpine3.7 , and attempts to build using:
```
docker buildx build --platform=linux/amd64 -t [my tag] .
```

I get "#6 0.398 standard_init_linux.go:228: exec user process caused: exec format error"
I get a similar error "exec container process `/bin/sh`: Exec format error" if I attempt to cross-compile build an image using podman or buildah using qemu-user-static on Fedora.

Such a cross-compile should work for most cases, so I believe something in the project is breaking it.

Have you compiled this ( along with peewee ) for arm64? Has anyone? Is that supposed to work?

**Comment by coleifer** [comment]
It should work just fine, sqlite obviously compiles on arm. I'm not really clear on what exactly the error is, but you can absolutely skip compiling sqlite and just install from the alpine repos instead if you're concerned about it.

**Comment by nanoscopic** [comment]
Okay. I'll see if I can replicate the issue on an actual arm64 device. If I can't I'll attempt to determine why the cross-compile doesn't work and report a better bug describing why it fails.
