### ISSUE TITLE
Response time when docker is disconnected from internet

### ISSUE THREAD

**Issue by eturfboer** [coleifer/sqlite-web#158]
I am using sqlite web on docker through the image on [DockerHub](https://hub.docker.com/r/coleifer/sqlite-web).

I had some planned and unplanned internet outages recently. I noticed that, when the internet is out, the website starts responding very slowly on requests. It is like something is going out to the internet and needs to timeout before showing the requested webpage.

Anything I use is internal network and runs fine. When internet is back up, system is smooth.

**Comment by coleifer** [comment]
It's very likely the google fonts request embedded in the CSS. I've gone ahead and removed that.
