### ISSUE TITLE
Set up action to publish to GitHub container registry

### ISSUE THREAD

**Issue by assyrus-favolo** [coleifer/sqlite-web#163]
Since you said you didn't want to mess with DockerHub in #151 would you instead consider publishing your image to GitHub's container registry? It allows you to stay on the same platform and it can be automated by using Actions

**Comment by coleifer** [comment]
I'm not interested at the moment in trying to disentangle the wilderness that is github actions and container stuff.

**Comment by assyrus-favolo** [comment]
I understand

**Comment by amoralesc** [comment]
@coleifer Are you open to PRs that implement this feature through GitHub Actions?
