### ISSUE TITLE
Primary Key Not Recognized

### ISSUE THREAD

**Issue by rileyamos** [coleifer/sqlite-web#165]
I'm running a docker container with a new instance of sqlite-web. The primary key of my table is not recognized which prevents the edit/delete functionality in the content tab. Primary Key is not checked for column `id` in the structure -> columns table even though it can be seen in the schema above.

![CleanShot 2024-09-11 at 09 43 16@2x](https://github.com/user-attachments/assets/03521c2c-207e-46c2-8faf-d61e58c9fd4d)

**Comment by coleifer** [comment]
The docker image on dockerhub is hopelessly out-of-date most likely that's the issue. You can build the docker image yourself, the `Dockerfile` is included in the repo.
