### ISSUE TITLE
Error in docker

### ISSUE THREAD

**Issue by chan-stephane** [coleifer/sqlite-web#166]
Hi, 
Someone know, how to solve this ? after i refresh the web it work 

![image](https://github.com/user-attachments/assets/1b23b328-8842-478d-8139-e6bbf7891c72), 
when i try to see logs in docker i have this : 

![image](https://github.com/user-attachments/assets/34f71681-cb49-4c93-a5b5-500e2876b71d)

**Comment by coleifer** [comment]
The docker image from dockerhub is really out-of-date. If you want to use Docker, then build the image fresh using the dockerfile provided in the repo.
