### ISSUE TITLE
Feature Request: add Edit/Delete to Query results listing

### ISSUE THREAD

**Issue by belzecue** [coleifer/sqlite-web#167]
Often I'll run a query and want to immediately edit a row, but the Edit/Delete actions only show up when viewing the Content listing.  Which means I have to copy the Id and do a manual update in the Query tab.  Would it make sense to include the Edit/Delete column in the Query listing too, same as how it works under Content?  Hopefully the only complication would be needing to exclude this column from exports.  Thanks.

**Comment by coleifer** [comment]
The reason we don't have that is because it's not necessarily clear if the primary-key has been selected when the query is run.

**Comment by coleifer** [comment]
Closing for now.

**Comment by belzecue** [comment]
Here's a browser javascript workaround for others facing this issue:

Create a javascript bookmark in your browser named something like "Edit Row ID".

The bookmark javascript is:

> javascript:xAFBM=document;aAFBM=xAFBM.location.href.replace('query','update');dAFBM=encodeURIComponent(window.getSelection());open(aAFBM+btoa(dAFBM));void 0;

Now, when you've run a query and have the list of results -- assuming you have an Id primary key defined in your table-- find the row you want to edit, double-click the row ID value with your mouse to select/highlight the number, then click on the "Edit Row ID" bookmark in your bookmarks bar.  A new window will open with sqlite-web in Update mode for that row.

You can define a second javascript bookmark for deletes that works the same way.  Just duplicate the bookmark javascript and substitute 'delete' for 'update'.

**Comment by coleifer** [comment]
Added experimental support for edit/delete on query view: d1ad225aeb6cb2a5716b6dfec447d5a5738ff061

Just looks to see if a column matching the primary key was selected (no support for composite keys planned).
