### ISSUE TITLE
RowID

### ISSUE THREAD

**Issue by x0x7** [coleifer/sqlite-web#18]
It would be really nice if the content tab showed rowid as well.  I think just changing the sql from select * to select rowid,* will do it.

**Comment by coleifer** [comment]
I'm not sure I agree that makes sense. If you don't actually declare your primary key column why would you necessarily want to see it when browsing your table? Or, if you want to see your rowids, just include `id integer not null primary key` when creating your tables.

As a workaround, you can always open the query tab and run `select rowid, * from 'mytable'`
