### ISSUE TITLE
The content tab is not refreshed when the structure of the database is changed.

### ISSUE THREAD

**Issue by martdi** [coleifer/sqlite-web#20]
When a column is added or dropped from a table, the content tab is not refreshed.

If you drop a column, visiting the tab will return a server error: 

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

If you add a column, it will not be displayed.

Closing and restarting the application will resolve the issue.

**Comment by coleifer** [comment]
That's kind of a bad one :/  I'll look into this soon, my personal time is kind of limited but I am aware of this and hope to fix it shortly.

**Comment by leeahoward** [comment]
related issue.  If a table is created by another app while this is running then viewing the table info /<table> gives the same result as above and "error table already exists" is logged to the console.  I think the model information is not getting updated.

**Comment by coleifer** [comment]
Fixed the first issue, related to refreshing the content tab.
