### ISSUE TITLE
How to make database readonly?

### ISSUE THREAD

**Issue by achourasia** [coleifer/sqlite-web#21]
Is it possible to configure and run this, such that no modification can be made to the database? This way the database is readonly, the end user could only query it. Alternatively, adding support for authentication for making changes to the database will be nice.

**Comment by achourasia** [comment]
Simplest idea may be to make the the database file readonly in the file system.

**Comment by coleifer** [comment]
This is beyond the scope or goal of the project. The project assumes that if you have permission to run sqlite-web and access a particular database, that you can then modify it.
