### ISSUE TITLE
preserve ordering on "previous" and "next" table content links

### ISSUE THREAD

**Issue by abhi-shetty** [coleifer/sqlite-web#23]
When I order table content by a specific column in content view and rows span across multiple pages, the "previous" and "next" links at the bottom of the page don't preserve ordering arguments. The Next and Previous pages start with no ordering.

Adding the ordering  for next and previous links in table_content.html seems to fix the issue for me

```
<         <a href="{{ url_for('table_content', table=table, page=previous_page) }}">&larr; Previous</a>
---
>         <a href="{{ url_for('table_content', table=table, page=previous_page, ordering=ordering) }}">&larr; Previous</a>
60c60
<         <a href="{{ url_for('table_content', table=table, page=next_page) }}">Next &rarr;</a>
---
>         <a href="{{ url_for('table_content', table=table, page=next_page, ordering=ordering) }}">Next &rarr;</a>

**Comment by coleifer** [comment]
Fixed, thanks for bringing this to my attention!
