### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by hugowan** [coleifer/sqlite-web#24]
classic unicode issue, please fix, thanks

**Comment by coleifer** [comment]
Where at chili-dawg??

**Comment by hugowan** [comment]
File "/usr/lib/python2.7/site-packages/sqlite_web/sqlite_web.py", line 543, in value_filter
    value = escape(value)

**Comment by coleifer** [comment]
Does the table this occured on have any BLOB columns? Also, what version or commit of sqlite-web are you using?

**Comment by coleifer** [comment]
I ask because in 10adccb10d3610b0e5c6a3f0c9d79024b9977952 I fixed a very similar issue.

**Comment by hugowan** [comment]
Yes, you are right. There have BLOB column.
ver: sqlite-web (0.1.5)

**Comment by coleifer** [comment]
I've released a new version, 0.1.6, that contains the aforementioned fix. Update your library and then if you are still running into this issue please either create a new ticket or comment on this one.

**Comment by hugowan** [comment]
Nice work. fixed. 👍🏻
