### ISSUE TITLE
Creating Table in sqlite-web browser and BOOL data type is returning INTEGER

### ISSUE THREAD

**Issue by victordomin** [coleifer/sqlite-web#25]
When creating tables in sqlite_web browser, I am running into trouble when trying to set the data type of a given field to `BOOL`; it instead returns `INTEGER`. The bottom three key-value pairs are supposed to be a `BOOL` (see image):

![image](https://cloud.githubusercontent.com/assets/14811476/20010585/9b996406-a276-11e6-81f0-ad01e3619b63.png)

When I go to the "Create Column" page and name a field and set its data type to `BOOL`, it is properly displaying `BOOL` from the dropdown box. However, after hitting the "Add Column" button and returning to the `structure` page, both the SQL and the columns sections show the data type as `INTEGER`.

Am I missing something here? Is this normal behavior? Is `INTEGER` functioning as a `BOOL` in a C-like manner where the field value 0 = `false` and 1 = `true`?

**Comment by coleifer** [comment]
SQLite does not have a boolean type, so behind-the-scenes we use an integer field with 0 and 1. These are really the only data-types supported: https://www.sqlite.org/datatype3.html

So there's not even varchar, just TEXT.

**Comment by victordomin** [comment]
Thanks for getting back to me! I sort of figured that's what was going on. I'm not the most familiar with SQLite yet—probably should have spent more time in the docs.

Thanks again!
