### ISSUE TITLE
peewee.OperationalError: Connection already open

### ISSUE THREAD

**Issue by kyleabens** [coleifer/sqlite-web#28]
Hello,

I already did pip install and now I'm entering '$ sqlite_web my/path' and it keeps saying 'peewee.OperationalError: Connection already open'  I'm not sure how to get around this.  Any ideas as to why it's throwing that error?

Thanks in advance!

**Comment by cet900** [comment]
I have the same problem, what was the solution @kyleabens ?
Thanks!

**Comment by cet900** [comment]
It seems to not happen when running with the -d flag, but that seems like the wrong solution!? Is this an issue?
