### ISSUE TITLE
Content Tab - Attribute Error

### ISSUE THREAD

**Issue by ossie-git** [coleifer/sqlite-web#36]
Hi,

I just installed sqlite-web using pip and started to use it.  Most of the functionality seems to work.  However, whenever I try to access the Content tab, it throws an error:

```
AttributeError: 'AutoField' object has no attribute 'db_column'
```

I tried it on using both Python 2.7 and Python 3.6 and both threw the same error.

This behavior was consistent across all SQLite databases I tried (including the http://www.sqlitetutorial.net/download/sqlite-sample-database/?wpdmdl=94 and https://github.com/jpwhite3/northwind-SQLite3).  Any ideas?  Thanks.

**Comment by ossie-git** [comment]
Just a small update.  When I clone the repository and run:

```
python3 sqilte_web.py "/path/to/sqlite.db"
```

it seems to work fine.  So the problem seems to be in the pip package

**Comment by coleifer** [comment]
Thanks, pushed 0.2.0. That bug was because Peewee 3.0 was released and there were some incompatibilities between the sqlite-web on PyPI and the latest version of Peewee. Should be safe to use the pypi version again. Thanks for reporting.

**Comment by ossie-git** [comment]
Just tried it out and the new version works fine.  I think you just won the prize for fastest issue closed 👍 Thanks.
