### ISSUE TITLE
Edit with Spreadsheet UI

### ISSUE THREAD

**Issue by mbarkhau** [coleifer/sqlite-web#39]
I've been looking for a hosted alternative to Google Sheets, for relatively small datasets. If a table could be edited like a spreadsheet, this would certainly be a candidate.

I know this opens up a whole can of worms on the concurrent editing side of things, but at least for our use case it would be fine to simply detect the concurrent edit and reject it with an error message.

**Comment by coleifer** [comment]
I don't have plans for adding this any time soon.

**Comment by coleifer** [comment]
We don't have spreadsheet-style editing, but I've added basic support for inserting, updating or deleting individual rows.
