### ISSUE TITLE
Secure Authentication

### ISSUE THREAD

**Issue by ekawahyu** [coleifer/sqlite-web#44]
What would be the better way of doing authentication rather than modifying the Python code where the line saying `password = None` to `password = 'mypassword'`? Thanks.

**Comment by coleifer** [comment]
You can specify it from the command-line using `-P` or `--password`. This will cause you to be prompted to securely enter the password.

**Comment by ekawahyu** [comment]
But if I run it as systemd service, `ps -ax | grep sqlite_web` would reveal the `-P` option to other users in the system. I am still trying to figure out how I can actually hash the password and not worry about keeping it as a plain text. Any suggestion? Thank you.

**Comment by coleifer** [comment]
It should not -- it will prompt you for a password which is collected securely.

**Comment by coleifer** [comment]
For what it's worth, if you're running it as a daemon, it might make sense to put nginx/apache in front of it and use nginx/apache basic auth to secure things.

**Comment by ekawahyu** [comment]
alright, cool, thank you!
