### ISSUE TITLE
[Feature Request] Adding First and Last Navigation Buttons

### ISSUE THREAD

**Issue by ekawahyu** [coleifer/sqlite-web#45]
This sqlite-web really is good! After using it for a while, I am thinking about having a simple additional feature: first and last navigation buttons, aside from previous and next buttons at the bottom. I find myself always have to look at the last page number and typing it into the address bar manually all the time when I wanted to see the data are actually stored. Thank you.

**Comment by coleifer** [comment]
09f971f5fcd8ee7b69ac97f5c59e249ef9885297
