### ISSUE TITLE
Right-click enabling

### ISSUE THREAD

**Issue by patarapolw** [coleifer/sqlite-web#46]
I really want to make a column a little wider, to make it easier to read.

I actually plan to something like this in Handsontable (which is right-click enabled), but it seems that I have to create a lot of API's...

OK, I made it resizable https://github.com/coleifer/sqlite-web/pull/47 but right-click enabled (jQuery-contextMenu, perhaps) is another subject...

**Comment by coleifer** [comment]
I'm going to pass for now.
