### ISSUE TITLE
Request: new option to support base url path for reverse proxy support

### ISSUE THREAD

**Issue by barbequesauce** [coleifer/sqlite-web#48]
I have nginx running as a reverse proxy for all my local apps, exposing them to the internet with some security layered in. Most of my (cherrypy) apps have an option to set a base URL path, allowing me to bake in a subdirectory into the non-proxied server's url...

`http://privvateserver.local:8080/appname/`

Then in the nginx config I can do something like this...

```
  location /appname/ {
    proxy_pass http://privateserver.local:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect http:// https://;
  }
```

to allow access like this:

`https://publicserver.ontheinternet.com/appname/`

I've tried various forms of the nginx rewrite directive, but the css keeps getting hosed up. Setting a base URL path would (hopefully) avoid that... thoughts?

**Comment by coleifer** [comment]
Just pushed 62be3254033d73b13737d7135f11794ce0cdc103 to the `master` branch. You can specify a URL prefix using "-u /appname".

Please give it a try and let me know if that addresses the issue for you.

**Comment by barbequesauce** [comment]
Works like a charm! Thanks! 

This is a great piece of software...
