### ISSUE TITLE
always tries to go to 127.0.0.1

### ISSUE THREAD

**Issue by Wqrld** [coleifer/sqlite-web#51]
i am currently running sqlite3 behind a caddy proxy to add basic authentication but sqlite3 always tried to go to 127.0.0.1/something after some requests which doesnt work. would you be able to make it go to a specific url using cli arguments?

**Comment by coleifer** [comment]
> but sqlite3 always tried to go to 127.0.0.1/something after some requests which doesnt work

Huh? Where? Can you be specific?

**Comment by Wqrld** [comment]
In the browser when creating dbs or adding columns, the post request works fine but where it then redirects you is broken.

**Comment by coleifer** [comment]
The redirects should not include the host, I wouldn't think. We're not using any special APIs, this is just a standard Flask app.

**Comment by coleifer** [comment]
Perhaps you've got a misbehaving proxy...I'm not familiar with caddy but presumably it would rewrite redirects?
