### ISSUE TITLE
Feature request: URL highlighting, file preview

### ISSUE THREAD

**Issue by robmarkcole** [coleifer/sqlite-web#52]
Hi 

I am using sqlite to store info on a photo collection, I insert the file path as a TEXT field and can view the url via sqlite-web. I can view the file by copy-paste into a browser tab, but what would be even nicer would be:
1) URL highlighing, so I could just click the URL to preview the photo in another tab
2) Even nicer, a quickview of the file

This possible?
Cheers

![image](https://user-images.githubusercontent.com/11855322/47550672-db25a800-d8f7-11e8-8860-c2c5354888d4.png)

**Comment by coleifer** [comment]
These are pretty niche use-cases to my thinking. Not really interested in maintaining such.
