### ISSUE TITLE
CSV import appears broken

### ISSUE THREAD

**Issue by az5112** [coleifer/sqlite-web#57]
After trying to import a simple CSV file i receive the following message:

Error importing file: iterator should return strings, not bytes (did you open the file in text mode?)

Steps to reproduce
1) `echo -e "col1,col2\n1,2" > test.csv`
2) `sqlite_web empty.sqlite`
3) Create table test
4) Click the **Import** tab, select file _test.csv_ (created in step 1), set **Create columns for unknown keys** to **Yes**

After clicking **Import** the error will be reported.

**Comment by bhavicp** [comment]
I'm getting the same here, Running python 3,6,5 - Looking around it looks like it might actually be related to peewee and the thaw method?

**Comment by coleifer** [comment]
945d8d5ba29a520510db4007c148e42edb04638d

**Comment by coleifer** [comment]
This is now fixed. The issue ran rather deep and had to do with the way werkzeug exposes file upload data, plus an incompatibility in the API of a particular type of stdlib temporary file with the usual file-like api.

Released 0.3.6 to pypi, thanks for reporting.
