### ISSUE TITLE
Can I open multiple databases?

### ISSUE THREAD

**Issue by abhijitnandy** [coleifer/sqlite-web#59]
Is it possible to open multiple databases on the same port?

**Comment by wyv3rnnn** [comment]
i'd also like to know the answer to this question. also why did the author close the issue instead of giving an answer???

**Comment by coleifer** [comment]
I'm not sure how well it would work, but you can try opening the query tab and running an ATTACH query to attach a 2nd database.

**Comment by banjuer** [comment]
> I'm not sure how well it would work, but you can try opening the query tab and running an ATTACH query to attach a 2nd database.

but how can i manage multiple databases by docker ?

**Comment by coleifer** [comment]
You won't be able to very easily.
