### ISSUE TITLE
How to specify web password when using docker ?

### ISSUE THREAD

**Issue by misiek303** [coleifer/sqlite-web#62]
Would be cool to pass the password to the app via docker.

**Comment by jrebey** [comment]
As per the instructions:

`-P`, `--password`: prompt for password to access sqlite-web. Alternatively, the password can be stored in the "SQLITE_WEB_PASSWORD" environment variable, in which case the application will not prompt for a password, but will use the value from the environment.

So in docker, -e "SQLITE_WEB_PASSWORD=yourpassword"

**Comment by coleifer** [comment]
Thanks @jrebey
