### ISSUE TITLE
Error when run sqlite-web as module

### ISSUE THREAD

**Issue by vx1920** [coleifer/sqlite-web#65]
I install sqlite-web into Windows installation of Python and I try to run it as "module" using "python.exe -m sqlite_web file.db" command line. I use my own py.bat with proper full path to python.exe inside, I hope I don't use PythonHome\scripts.  I run py.bat it in Windows command line prompt (cmd.exe).
 I got following results:
``
d:\My\ProPy\SQLite>py -m sqlite_web NorthWind.db
Run: d:\InstSoft\Python\Python3x64\Python.exe
Arg: -m sqlite_web NorthWind.db
Traceback (most recent call last):
  File "d:\InstSoft\Python\Python3x64\lib\runpy.py",
    line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\InstSoft\Python\Python3x64\lib\runpy.py",
    line 85, in _run_code
    exec(code, run_globals)
  File "d:\InstSoft\Python\Python3x64\lib\site-packages\sqlite_web\__main__.py",
    line 1, in <module>
    from sqlite_web import main
ImportError: cannot import name 'main' from 'sqlite_web'
 (d:\InstSoft\Python\Python3x64\lib\site-packages\sqlite_web\__init__.py)
d:\My\ProPy\SQLite>

I did look into sqlite_web  \\ \_\_main\_\_.py and I decide to fix it by modifying "import" statement in line 1 by adding '.' before sqlite_web as of:
 from .sqlite_web import main

Everything is much better after the above fix: I got InternetExplorer started with proper tables shown. Maybe it make sense to fix sqlite_web/\_\_main\_\_.py, it looks like there is bug in "import".
``
 P.S. ``
 Do I really need flask/sqlite_web executables inside PythonHome\scripts folder if I start sqlite_web
using above "py -m sqlite_web filename" ?

**Comment by coleifer** [comment]
The readme shows how to run it: https://github.com/coleifer/sqlite-web#usage
