### ISSUE TITLE
'Created' and 'Modified' datetimes can be incorrect depending on deployment system

### ISSUE THREAD

**Issue by dnk8n** [coleifer/sqlite-web#66]
Please see http://covid-19-backend.now.sh, a recent project I have been playing with.

As you can see, the creation dates are out. It would be great to have a config that allows end-users to omit certain rows on the front page. Personally I would also like to add a link to the SQLite database to the front page (http://covid-19-backend.now.sh/download/db).

Maybe there is already a Flask native way of extending and tweaking inherited templates? If you know how, I would very much value your insight in terms of this project.

**Comment by coleifer** [comment]
Yeah, I'd suggest that you just modify the templates to your preference or extend the source code.
