### ISSUE TITLE
Boolean values only appears as true

### ISSUE THREAD

**Issue by jmalab1** [coleifer/sqlite-web#69]
First of all, Amazing job with this! Thanks for making it open source.

The issue I'm having is that the boolean values are appearing as true on the table even though they are really false. please refer to the images below.
<img width="892" alt="Screen Shot 2020-08-11 at 12 56 32 PM" src="https://user-images.githubusercontent.com/48142901/89926174-7c1b4b00-dbd2-11ea-8b45-eb5c7c93186f.png">

Using https://sqliteonline.com/ just for reference:
<img width="1072" alt="Screen Shot 2020-08-11 at 12 58 28 PM" src="https://user-images.githubusercontent.com/48142901/89926190-80dfff00-dbd2-11ea-9104-09f4f87bab91.png">

Table structure:
<img width="349" alt="Screen Shot 2020-08-11 at 12 54 00 PM" src="https://user-images.githubusercontent.com/48142901/89926201-86d5e000-dbd2-11ea-91bf-4d4b0d2ee000.png">

**Comment by coleifer** [comment]
sqlite doesn't have a boolean type. The sqlite-web follows the sqlite convention, which is to use 0 and 1 and an integer column type.

https://www.sqlite.org/datatype3.html#boolean
