### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by minusf** [coleifer/sqlite-web#7]
i know it is kind of late, but would you consider picking
some kind of name/nickname for your project?
there is already https://github.com/sqlitebrowser/sqlitebrowser/
and i would like to create a package for openbsd
so its possible to easily install and use it locally...
sqlitebrowser (not sqlite-browser) is way to heavy
on dependencies.

peewee is also not called "orm" :)

**Comment by minusf** [comment]
it would also help the packaging a lot if you created a new release
(maybe also on pypi ;-)

**Comment by coleifer** [comment]
Ahh, yeah -- I did not realize there was already a ``sqlitebrowser``, which is unfortunate. I'll consider renaming this, but I'd hate to break any existing setups that point to the `sqlite-browser` package.

**Comment by minusf** [comment]
the decision is of course yours, but i think it would be better to bite
the bullet earlier than later...  it is not unheard of, projects changing
names, even multiple times.  this github project page would simply
point people to the next version with the new name.  the old links,
etc would not break.  it's not like it never happened before :]

**Comment by coleifer** [comment]
You're totally right -- I'll start thinking of a better name :)

**Comment by coleifer** [comment]
Renamed to sqlite-web, which a quick google search revealed to be available.
