### ISSUE TITLE
New feature: history or favorites

### ISSUE THREAD

**Issue by z4rn0x** [coleifer/sqlite-web#70]
Hello! Thank you for what you did with this app, I'm using it quite often on my Home Assistant. I'd like to submit an idea that could be a great feature for this app.
I'm using the same requests on a regular basis, so would it be possible either to keep an history of the requests recently used (like the 10 last ones? or even better, to save some favorite requests?) I know nothing at programming, so unfortunately I can't submit anything on Github.
Hope you'll like the idea!

**Comment by coleifer** [comment]
I'm going to pass, but that's certainly an interesting idea. If I change my mind I'll reopen.
