### ISSUE TITLE
Is it possible to enable TLS encryption in the server?

### ISSUE THREAD

**Issue by nidoro** [coleifer/sqlite-web#71]
What is the simplest way to enable HTTPS connection in the server? Do I have to run it behind some other software? I looked around but didn't find a straight forward answer to this question. Thanks!

**Comment by coleifer** [comment]
I think most people have used nginx in front to handle SSL, but it is fairly easy to add so I've gone ahead and added support for 3 new options:

* -c / --cert - ssl cert file
* -k / --key - ssl key file
* **or**, -a / --ad-hoc for ad-hoc ssl context

**Comment by nidoro** [comment]
Thanks for that, I just tested and it works nicely. I just have a few follow up comments/questions:

1. Before it worked I had an issue with setting the host option (-H). I tried to set the domain name of my server but it failed, so did its external ip address. It worked by putting 0.0.0.0. I don't know if that's normal, just pointing that out.

2. What does this warning means? Should I do something about it before using it for accessing my production database remotely?
```
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
```

**Comment by coleifer** [comment]
See: https://serverfault.com/questions/78048/whats-the-difference-between-ip-address-0-0-0-0-and-127-0-0-1

The warning means you're running using the flask dev server. sqlite-web exports a wsgi app and you can use a different wsgi server if you wish.

**Comment by nidoro** [comment]
I'm trying to make it work with gunicorn, but I'm struggling because I have no experience with wsgi servers nor flask applications. I could not figure out how to pass the database path to the flask app. Can you give some guidelines on how to use sqlite-web with another wsgi server?

**Comment by coleifer** [comment]
I'm not quite sure why you would be set on running it with gunicorn, especially if you have no experience with wsgi/flask, (not to mention the fact that sqlite only supports 1 writer at a time). That being said, you would just want to look at what is happening in `sqlite_web.main()` and initialize the app, then pass it off to your wsgi server.

**Comment by nidoro** [comment]
Well, I don't know what is entailed in that warning message. Since it recommends using a production WSGI I thought I would give it a try.

Anyway, thanks for the application.

**Comment by coleifer** [comment]
I've gone ahead and added an example here: https://github.com/coleifer/sqlite-web/blob/master/wsgi_example/wsgi_example.py

**Comment by nidoro** [comment]
Thanks again! I appreciate that!
