### ISSUE TITLE
Can't see changes after modifying the html files

### ISSUE THREAD

**Issue by Blue-Davinci** [coleifer/sqlite-web#72]
Hello @coleifer ,
This is a very amazing application and i love your work,
Am using this for learning and I have an issue, 
Whenever i try to change the templates, once i execute the application again, this changes do not persist,
Is there a reason for this? or am i doing something wrong?
I've tried the automatic rendering option as well as checked out the javascript and css files
but i don't see any issues.
Thank you.

**Comment by coleifer** [comment]
I'm not sure. The templates are just html files. You should be able to change them, then restart the application and see the changes.

**Comment by Blue-Davinci** [comment]
@coleifer There seems to be an issue.
I managed to render my modded html file, but here's the kicker:
I had to change the **app from running on port 8080 to 5000**
When i did that, i restarted and now it's displaying the changes to the HTML files.
I don't know why this happens because if i default back to 8080 it revers back.
Any ideas?
Btw thanks for the quick response.

**Comment by coleifer** [comment]
That makes no sense to me.

**Comment by Blue-Davinci** [comment]
So found the issue, it had been cached under that port. Clearing the cache also does the trick.
Thanks and love the work.
