### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by AlpacaJ** [coleifer/sqlite-web#76]
I'm trying to enable foreign key support to test Cascade Delete, but get the message "_You can only execute one statement at a time._"

My Query looks like:

```
PRAGMA foreign_keys = ON;

DELETE
FROM "XXX"
WHERE Field = 01
```

Is there a way to get Cascade Delete working?

**Comment by coleifer** [comment]
That is a per-connection setting and connection management (and other pragmas) are opaque from the user at the present.
