### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by paroczigergo** [coleifer/sqlite-web#78]
### Issue description

I'm trying to run this : `sqlite_web ~/mydb.db`, but the result always  `RecursionError` for 
` File "/home/pi/.local/lib/python3.7/site-packages/playhouse/reflection.py", line 688, in _create_model`

I tried to increase the  recursion limit `sys.setrecursionlimit(100000)`, but in the end I got only `Segmentation fault` text message. 

I also tried with python 2.7 and 3.7, but nothing changed.

![image](https://user-images.githubusercontent.com/3731322/112692098-ac240f80-8e7e-11eb-8c7b-58bac76d16e7.png)

#### What's the expected result?

- working sqlite_web

**Comment by coleifer** [comment]
Can you share the schema?

**Comment by paroczigergo** [comment]
Sorry, it was my bad. I created a  circular reference in the schema.
