### ISSUE TITLE
Docker suggestion

### ISSUE THREAD

**Issue by DannyBen** [coleifer/sqlite-web#79]
Right now the docker instructions in the README assume that users downloaded the repository.

May I suggest:

1. Change the README docker instructions to use the public image on DockerHub.
2. Ensure that the [public docker image](https://hub.docker.com/r/coleifer/sqlite-web) is automatically updated via build triggers.

**Comment by coleifer** [comment]
I don't really have much interest in maintaining the docker image up-to-date when it's trivial to build it yourself. The Dockerfile itself should really be sufficient and you're welcome to set-up your own build if you'd like.
