### ISSUE TITLE
use of absolute web links prevent functioning with reverse-web-proxy

### ISSUE THREAD

**Issue by kx1t** [coleifer/sqlite-web#80]
Hi there,

I have been trying to run SQLite-Web behind a reverse web proxy (nginx-based), with the following proxy-pass implementation:
```
location /acarsdb/ {
        proxy_pass http://10.0.0.188:8080/;
}
```
In this case, it exposes SQLite, running on `http://10.0.0.188:8080` as `https://ramonk.net/acarsdb`. 

The issue I came across is that `SQLite-Web` has implemented hardcoded links to root of the website for the table names (see for example the `messages` table in the link above), rather than relative links from whichever directory is used as root directory for `SQLite-Web`. This makes it impossible to run this (further excellent) app in a multi-tenant docker environment headed by a reverse web proxy.

Would you consider updating the code to use relative links rather than absolute links?
Thanks!
k1xt

**Comment by evanlinde** [comment]
@kx1t You might want to try the `--url-prefix `*`prefix`* option. This should allow you to get sqlite-web running at http://10.0.0.188:8080/acarsdb and might fix your link issue.

**Comment by kx1t** [comment]
Yes, your suggestion in combination with the change to the reverse proxy shown below, works. Thanks for that, @evanlinde !
I still think this would be a valid enhancement request, but obviously it's now a lot less urgent for me.
I am leaving it up to the repo owner to assess and adjudicate to his liking.

And... thanks for this tool! It has helped me a lot, especially the ability to get a quick handle on "whats going on" from anywhere, even if I'm on my mobile. Much appreciated!

**Comment by coleifer** [comment]
The url-prefix parameter exists exactly for this reason. No change needed as far as I'm concerned.
