### ISSUE TITLE
running on aws - arm based (t4) AMI LInux 2 image

### ISSUE THREAD

**Issue by johndpope** [coleifer/sqlite-web#87]
sqlite_web -H 0.0.0.0 -p 8085 -x ./db/data-go.sqlite -d true -u /dbgo
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'sqlite_web.sqlite_web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.31.82.190:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'sqlite_web.sqlite_web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.31.82.190:8085/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/peewee.py", line 5141, in __init__
    super(BareField, self).__init__(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/peewee.py", line 4491, in __init__
    self.null = null
**MemoryError**

During handling of the above exception, another exception occurred:

**MemoryError**

I have same code running fine on x64 image.

**Comment by coleifer** [comment]
I appreciate you taking the time to make a nice issue, but I really can't debug this. If you can pinpoint the issue feel free to let me know. It sounds, however, like maybe you don't have enough RAM?
