### ISSUE TITLE
not an issue - fyi - pm2 integration for boot up / visualization of uptime / logs / auto restart on mem usage

### ISSUE THREAD

**Issue by johndpope** [coleifer/sqlite-web#88]
<img width="1199" alt="Screen Shot 2021-09-22 at 4 30 18 pm" src="https://user-images.githubusercontent.com/289994/134293851-35f6a641-4c3b-409c-939d-f31ac3a23543.png">

**package.json**
```javascript
{
    "apps" : [{
      "name"        : "backend_go",
      "script"      : "./server"
    },{
      "name"        : "sqlweb-currency",
      "script"      : "sqlite_web",
      "args":"-H 0.0.0.0 -x ./db/currencyData.sqlite -d true ",
      "interpreter" :"/usr/bin/python3"
    },{
      "name"        : "sqlweb-data",
      "script"      : "sqlite_web",
      "args":"-H 0.0.0.0 -p 8085 -x ./db/data-go.sqlite -d true  ",
      "interpreter" :"/usr/bin/python3"
    }]
}
```

you can call 
**pm2 start package.json**

**pm2 ls** to inspect process - 
**pm2 save** 
**pm2 startup** to persistent across boot
**pm2 restart name** to cycle process
(I understand it's possible to use this style of system / but pm2 is nicer / do give it a try)

# code /etc/systemd/system/sqlite-web.service
[Unit]
Description=Auto start web sqlite
After=network.target

[Service]
Type=simple
ExecStart="/home/ec2-user/fundfi/backend_go/start-sqlite.sh"
TimeoutStartSec=0

[Install]
WantedBy=default.target

you can inspect the logs by typing
pm2 NAME logs
<img width="1046" alt="Screen Shot 2021-09-22 at 4 44 56 pm" src="https://user-images.githubusercontent.com/289994/134295509-60469ab8-0647-407f-ab12-a30ca05e0f5d.png">

**Comment by coleifer** [comment]
What is this doing here?

**Comment by johndpope** [comment]
Docker does make this redudant. But if you want to run bare metal on ec2 box - and persist sqlite_web across boot up - pm2 is nice option.
