### ISSUE TITLE
css issue in firefox

### ISSUE THREAD

**Issue by minusf** [coleifer/sqlite-web#9]
the `table_name` and `table-search` input fields do not show
their values in firefox (in chrome it works) because `.input-sm`
has a padding that pushes them out of view: `padding: 15px 10px;`

as far as i can say, in vanilla bootstrap that padding is smaller: `padding: 5px 10px;`

changing it to the bootstrap value makes them visible again.

**Comment by coleifer** [comment]
I'll try updating the stylesheet I'm using.
