### ISSUE TITLE
How to let client machine access the website?

### ISSUE THREAD

**Issue by lovelyplanet2019** [coleifer/sqlite-web#94]
I expose the db to IP but web does not load when  browse it at another machine by hostIP:8080.
Any idea how can I make the db acceseable from other machinr by IP?

sqlite_web --host 0.0.0.0 my_database

**Comment by coleifer** [comment]
You may have a firewall issue or something else going on, I couldn't say.

When running sqlite_web with `--host=0.0.0.0` then it should be reachable by others on the network (or internet if your computer is exposed to the public internet).

**Comment by lovelyplanet2019** [comment]
I have another website which is localhost:8888 at host then hostIP:8888 at client without problem.
The sqlite host localhost:8080 works but not hostIP:8080
I thought something else i ned to setup at host when using sqlite web.
Anyway thanks. I will try to change another port.

**Comment by coleifer** [comment]
That doesn't make any sense to me, because if the other website is listening on localhost it should be prevented from being accessible by another host..
