### ISSUE TITLE
Sqlite_web won't work if there is space in the path to sqlite_web 

### ISSUE THREAD

**Issue by dukenmarga** [coleifer/sqlite-web#96]
First of all, I'm grateful we have this piece of great software. Although simple, but can make life easier.
Thank you very much.

Secondly, when I tried to run sqlite_web, the terminal said sqlite_web cannot be found. I tried to install sqlite_web using pip inside virtual env.

```
cd ~/Documents/Software\ Project/web/ # note there is space between Software and Project
python3.9 -m venv venv39
source venv39/bin/activate
pip install sqlite_web
rehash
sqlite_web application/dev.sqlite3
```

Error:
`zsh: /home/duken/Documents/Software Project/web/venv39/bin/sqlite_web: bad interpreter: "/home/duken/Documents/Software: no such file or directory
`
It shows that the string is stopped after Software that indicate that it cannot read space after.

I tried to rename the directory and remove the space in between. Reinstall the package and runt sqlite_web, this time I can browse the database on the browser seamlessly.

But, I'm not sure whether this issue is regarding the path to sqlite_web or path to *.sqlite file itself.

**Comment by coleifer** [comment]
This has *nothing* to do with sqlite-web. This has everything to do with your janky zsh setup and possibly pip or whatever is setting up the paths when you activate your virtualenv.
