### ISSUE TITLE
Support being able to edit table

### ISSUE THREAD

**Issue by LunarTwilight** [coleifer/sqlite-web#98]
Could it please be possible to edit a DB's table (edit/add/delete rows) from the UI rather than needing to run SQL commands every time?

**Comment by coleifer** [comment]
No, no plans for this currently.

**Comment by spacewalkingninja** [comment]
yeah, like a year later I added this support https://github.com/spacewalkingninja/sqlite-web-NOT-SHIT

just install it by following instructions:
### Installation

```sh
$ pip install git+https://github.com/spacewalkingninja/sqlite-web-NOT-SHIT@master
```

**Comment by coleifer** [comment]
Lol clown I took a look at the diff (55 commits to achieve...[this?](https://github.com/coleifer/sqlite-web/compare/master...spacewalkingninja:sqlite-web-NOT-SHIT:master)). There are a few copy/paste/adjust-to-taste fails. Some good places where K.A. couldn't be assed to read a doc so he just sprays n' prays. Some other failures of imagination.

Limitations which the above author fails to disclose:

1. no way to differentiate between NULL and empty string
2. no way of handling blob/binary data
3. no multi-line text editing
4. no handling of composite primary-keys
5. disregards readonly flag
6. no validation or enforcement of data-types
7. no error handling in sight
8. builds some queries w/string concatenation and formatting, no parameterization
9. lol good luck if your table names or columns have spaces or other special characters
10. probably other stuff but I don't want to spend more than 5 minutes on this.

I know OP's feelings were hurt that I wouldn't upstream his changes but considering the above I think it's quite warranted.

**Comment by coleifer** [comment]
This has been added in master and, after a little while for people to have a chance to try it out, will be incorporated into the next release. Screenshots are on the README.
